/* kernel/net.c — Pinecore network-provider dispatch.
 *
 * Implements the kernel side of the BSD-sockets-shaped ABI declared in
 * net.h: active-provider slot, kernel-owned fd table (1024 entries),
 * 17 NET_SYS_* dispatch handlers that translate fd -> opaque provider
 * cookie before calling into the provider vtable, and a select() loop
 * that runs on top of the provider's per-cookie sock_poll.
 *
 * INT 0x80 is installed by net_init() with DPL=3 so DPMI Ring-3
 * clients can call it. The CPU stub (isr_stub_128) is generated by the
 * ISR_NOERR macro in boot/isr_stubs.asm and lands in isr_dispatch_inner
 * (idt.c), which routes int_no==128 here via net_dispatch.
 *
 * Concurrency: v1 takes the easy road. No locking on the fd table —
 * single active DPMI client at a time is the dominant pinecore
 * pattern, and the provider is responsible for its own internal
 * locking. We revisit when a real multi-client workload shows up.
 *
 * DNS: net_resolve() is a stub for v1 (returns ENOSYS); the real
 * resolver lives in a follow-on task.
 */

#include "types.h"
#include "net.h"
#include "idt.h"
#include "module.h"
#include "serial.h"
#include "pit.h"
#include "config.h"

extern int          strcmp(const char *, const char *);
extern unsigned long strlen(const char *);
extern void        *memcpy(void *dst, const void *src, uint32_t n);
extern void        *memset(void *dst, int c, uint32_t n);

/* CPU stub for INT 0x80 — generated by ISR_NOERR 128 in isr_stubs.asm. */
extern void isr_stub_128(void);

/* ------------------------------------------------------------------
 * Active provider slot — single-slot v1
 * ------------------------------------------------------------------ */
static const struct net_provider *g_active;

const struct net_provider *net_active_provider(void) {
    return g_active;
}

/* ------------------------------------------------------------------
 * Kernel fd table (1024 entries). fd is the user-facing handle;
 * cookie is the provider's opaque socket reference.
 * ------------------------------------------------------------------ */
struct fd_entry {
    int          in_use;
    pcnet_sock_t cookie;
};

static struct fd_entry g_fdtab[PCNET_FD_SETSIZE];

static int fd_alloc(pcnet_sock_t cookie) {
    int i;
    for (i = 0; i < PCNET_FD_SETSIZE; i++) {
        if (!g_fdtab[i].in_use) {
            g_fdtab[i].in_use = 1;
            g_fdtab[i].cookie = cookie;
            return i;
        }
    }
    return PCNET_EMFILE;
}

static void fd_free(int fd) {
    if (fd >= 0 && fd < PCNET_FD_SETSIZE) {
        g_fdtab[fd].in_use = 0;
        g_fdtab[fd].cookie = NULL;
    }
}

static int fd_lookup(int fd, pcnet_sock_t *out) {
    if (fd < 0 || fd >= PCNET_FD_SETSIZE) return PCNET_EBADF;
    if (!g_fdtab[fd].in_use)              return PCNET_EBADF;
    *out = g_fdtab[fd].cookie;
    return 0;
}

/* ------------------------------------------------------------------
 * Provider registration — EXPORT_SYMBOL'd at end of file so .kmd
 * providers resolve them via the kernel kexport table.
 * ------------------------------------------------------------------ */

static void log_register(const struct net_provider *p) {
    const char *stab = "stable";
    if (p->stability == NET_PROVIDER_EXPERIMENTAL) stab = "experimental";
    else if (p->stability == NET_PROVIDER_DEPRECATED) stab = "deprecated";
    serial_puts("net: registered provider '");
    serial_puts(p->name);
    serial_puts("' (");
    serial_puts(stab);
    serial_puts(") - ");
    serial_puts(p->description ? p->description : "");
    serial_puts("\n");
}

int net_register_provider(const struct net_provider *p) {
    if (!p || !p->ops)
        return PCNET_EINVAL;
    if (p->abi_version != NET_PROVIDER_ABI_VERSION)
        return PCNET_EINVAL;
    if (g_active)
        return PCNET_EADDRINUSE;

    if (p->ops->start) {
        int rc = p->ops->start();
        if (rc < 0) return rc;
    }
    g_active = p;
    log_register(p);
    return PCNET_OK;
}

void net_unregister_provider(const struct net_provider *p) {
    int i;
    if (!g_active || g_active != p) return;

    /* Close any still-open sockets via the provider before tearing down. */
    for (i = 0; i < PCNET_FD_SETSIZE; i++) {
        if (g_fdtab[i].in_use) {
            if (g_active->ops->sock_close)
                g_active->ops->sock_close(g_fdtab[i].cookie);
            g_fdtab[i].in_use = 0;
            g_fdtab[i].cookie = NULL;
        }
    }
    if (g_active->ops->stop) g_active->ops->stop();

    serial_puts("net: unregistered provider '");
    serial_puts(g_active->name);
    serial_puts("'\n");
    g_active = NULL;
}

/* ------------------------------------------------------------------
 * DNS resolver — RFC 1035 A-record query over UDP via the active
 * provider's sockets. Nameserver comes from PCORE.CFG net_dns_server.
 *
 * Single-question A query, RD=1. 5-second wall-clock budget per
 * attempt, one retry on timeout. Walks the answer section honoring
 * CNAME chains delivered in the same response (returns the first A
 * record found). Does NOT follow CNAMEs across separate queries.
 *
 * Blocks the caller until resolution finishes or the budget expires.
 * INT 0x80 lands via an interrupt gate (IF=0) — we sti around the
 * poll loop so the NIC IRQ + PIT tick run.
 * ------------------------------------------------------------------ */

#define DNS_PORT          53
#define DNS_TYPE_A         1
#define DNS_TYPE_CNAME     5
#define DNS_CLASS_IN       1
#define DNS_FLAGS_RD  0x0100   /* QR=0, OPCODE=0, RD=1 */
#define DNS_HDR_LEN       12
#define DNS_MAX_NAME     255   /* RFC 1035 §2.3.4 */
#define DNS_MAX_PKT      512   /* UDP DNS w/o EDNS0 */
#define DNS_TIMEOUT_TICKS 500  /* 100 Hz PIT → 5 s */

static inline void wbe16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)(v >> 8); p[1] = (uint8_t)v; }
static inline uint16_t rbe16(const uint8_t *p)   { return ((uint16_t)p[0] << 8) | p[1]; }

/* Encode "a.b.c" as length-prefixed labels with a 0 terminator.
 * Returns bytes written on success, or -1 if the name is malformed
 * (empty, leading/trailing dot, empty label, label > 63, total > 255). */
static int dns_encode_qname(const char *host, uint8_t *out, int max) {
    int pos = 0;
    const char *p = host;
    if (!host || !*host) return -1;
    while (*p) {
        const char *dot = p;
        int label_len;
        while (*dot && *dot != '.') dot++;
        label_len = (int)(dot - p);
        if (label_len == 0 || label_len > 63) return -1;
        if (pos + 1 + label_len + 1 > max) return -1;
        out[pos++] = (uint8_t)label_len;
        for (int i = 0; i < label_len; i++) out[pos++] = (uint8_t)p[i];
        p = dot;
        if (*p == '.') {
            p++;
            if (!*p) return -1;     /* trailing dot */
        }
    }
    out[pos++] = 0;
    if (pos > DNS_MAX_NAME + 1) return -1;
    return pos;
}

/* Advance *pos past a domain name in the response, handling RFC 1035
 * §4.1.4 compression pointers. We don't follow them — just step over.
 * Returns 0 on success, -1 if the name is malformed. */
static int dns_skip_name(const uint8_t *buf, int buflen, int *pos) {
    int steps = 0;
    while (1) {
        uint8_t len;
        if (*pos >= buflen) return -1;
        if (++steps > DNS_MAX_NAME) return -1;
        len = buf[*pos];
        if (len == 0) { (*pos)++; return 0; }
        if ((len & 0xC0) == 0xC0) {
            if (*pos + 2 > buflen) return -1;
            *pos += 2;
            return 0;
        }
        if (len > 63) return -1;
        if (*pos + 1 + len > buflen) return -1;
        *pos += 1 + len;
    }
}

int net_resolve(const char *hostname, struct in_addr *out) {
    const struct net_provider_ops *ops;
    uint32_t dns_ip;
    pcnet_sock_t cookie = NULL;
    struct sockaddr_in sa;
    uint8_t  q[DNS_HDR_LEN + DNS_MAX_NAME + 1 + 4];
    uint8_t  r[DNS_MAX_PKT];
    uint16_t txid;
    int      qname_len, qlen;
    int      attempt, rc = PCNET_ETIMEDOUT;

    if (!hostname || !out) return PCNET_EINVAL;
    if (!g_active)         return PCNET_ENOPROVIDER;
    ops = g_active->ops;
    if (!ops->sock_create || !ops->sock_sendto ||
        !ops->sock_recvfrom || !ops->sock_poll || !ops->sock_close)
        return PCNET_ENOSYS;

    dns_ip = config_net_dns_server();
    if (dns_ip == 0) return PCNET_EHOSTUNREACH;

    /* Build header + question once; ID rotates per attempt. */
    memset(q, 0, sizeof(q));
    qname_len = dns_encode_qname(hostname, q + DNS_HDR_LEN,
                                 (int)sizeof(q) - DNS_HDR_LEN - 4);
    if (qname_len < 0) return PCNET_EINVAL;

    wbe16(q + 2, DNS_FLAGS_RD);
    wbe16(q + 4, 1);                 /* QDCOUNT */
    wbe16(q + DNS_HDR_LEN + qname_len,     DNS_TYPE_A);
    wbe16(q + DNS_HDR_LEN + qname_len + 2, DNS_CLASS_IN);
    qlen = DNS_HDR_LEN + qname_len + 4;

    if (ops->sock_create(AF_INET, SOCK_DGRAM, IPPROTO_UDP, &cookie) < 0)
        return PCNET_ENETDOWN;

    memset(&sa, 0, sizeof(sa));
    sa.sin_family      = AF_INET;
    sa.sin_port        = (uint16_t)((DNS_PORT << 8) | (DNS_PORT >> 8)); /* htons */
    sa.sin_addr.s_addr = dns_ip;     /* already network-order from config */

    /* s54 Tier-1: hardened TXID. The earlier `pit_ticks_get ^ attempt`
     * is predictable enough for an off-path attacker who knows roughly
     * when the query was issued. Mix in RDTSC's low half (much higher
     * entropy at boot) and a static counter that survives across calls
     * so even back-to-back resolutions within one PIT tick get distinct
     * IDs. Still not a CSPRNG — TODO for v2 — but raises the bar from
     * "trivially guessable" to "off-path attacker needs ~2^32 work to
     * land a poison". */
    static uint32_t g_resolve_seq = 0xA5A5A5A5u;
    uint32_t tsc_lo, tsc_hi;
    __asm__ __volatile__("rdtsc" : "=a"(tsc_lo), "=d"(tsc_hi));
    g_resolve_seq = g_resolve_seq * 1103515245u + 12345u + tsc_lo;

    for (attempt = 0; attempt < 2; attempt++) {
        uint64_t deadline;
        pcnet_ssize_t sent;

        txid = (uint16_t)(g_resolve_seq ^ (g_resolve_seq >> 16) ^
                          (uint16_t)(pit_ticks_get() + attempt));
        g_resolve_seq = g_resolve_seq * 1103515245u + 12345u;
        wbe16(q + 0, txid);

        sent = ops->sock_sendto(cookie, q, (uint32_t)qlen, 0,
                                (const struct sockaddr *)&sa, sizeof(sa));
        if (sent < 0) { rc = (int)sent; continue; }

        /* Poll with IRQs enabled so the NIC can deliver + PIT advances. */
        __asm__ __volatile__("sti");
        deadline = pit_ticks_get() + DNS_TIMEOUT_TICKS;
        while (pit_ticks_get() < deadline) {
            int got = ops->sock_poll(cookie);
            if (got < 0) { rc = got; break; }
            if (got & PCNET_POLL_RD) {
                struct sockaddr_in from;
                pcnet_socklen_t flen = sizeof(from);
                pcnet_ssize_t rlen;
                int p, ancount;

                memset(&from, 0, sizeof(from));
                rlen = ops->sock_recvfrom(cookie, r, sizeof(r), 0,
                                          (struct sockaddr *)&from, &flen);
                if (rlen < DNS_HDR_LEN) { rc = PCNET_ETIMEDOUT; continue; }

                /* s54 Tier-1: validate source. The response MUST come
                 * from the IP and port 53 we sent the query to. An
                 * off-path attacker spraying responses doesn't know our
                 * source port, but additionally constraining the source
                 * IP closes any provider that happens to leak the port
                 * (loopback's sendto doesn't actually allocate one). */
                if (from.sin_addr.s_addr != dns_ip) continue;
                if (from.sin_port != sa.sin_port)   continue;

                /* Match transaction id; mismatched response → keep waiting. */
                if (rbe16(r + 0) != txid) continue;

                /* s54 Tier-1: echo-check the question name. A response
                 * to query A with the question section of B is suspect,
                 * even if the txid matches. Compare byte-for-byte
                 * against what we sent — both are length-prefixed labels
                 * terminated by a zero byte. */
                {
                    int qpos = DNS_HDR_LEN;
                    int spos = DNS_HDR_LEN;
                    int mismatch = 0;
                    while (qpos < qlen - 4 && spos < (int)rlen) {
                        if (q[qpos] != r[spos]) { mismatch = 1; break; }
                        if (q[qpos] == 0) break;
                        qpos++; spos++;
                    }
                    if (mismatch) continue;
                }

                /* QR=1 + RCODE check (low 4 bits of flags[1]). */
                if ((r[2] & 0x80) == 0)       { rc = PCNET_EHOSTUNREACH; goto done; }
                switch (r[3] & 0x0F) {
                case 0:  break;                                /* NOERROR */
                case 3:  rc = PCNET_EHOSTUNREACH; goto done;   /* NXDOMAIN */
                default: rc = PCNET_EHOSTUNREACH; goto done;
                }

                ancount = rbe16(r + 6);
                if (ancount == 0) { rc = PCNET_EHOSTUNREACH; goto done; }

                /* Skip question section (we sent one). */
                p = DNS_HDR_LEN;
                if (dns_skip_name(r, (int)rlen, &p) < 0) { rc = PCNET_EHOSTUNREACH; goto done; }
                if (p + 4 > (int)rlen) { rc = PCNET_EHOSTUNREACH; goto done; }
                p += 4;

                /* Walk answers; first A record wins. CNAMEs in the
                 * chain are skipped — the A for the alias is normally
                 * included in the same response. */
                while (ancount-- > 0) {
                    uint16_t type, cls, rdlen;
                    if (dns_skip_name(r, (int)rlen, &p) < 0) break;
                    if (p + 10 > (int)rlen) break;
                    type  = rbe16(r + p);     p += 2;
                    cls   = rbe16(r + p);     p += 2;
                    p += 4;                   /* TTL */
                    rdlen = rbe16(r + p);     p += 2;
                    if (p + rdlen > (int)rlen) break;
                    if (type == DNS_TYPE_A && cls == DNS_CLASS_IN && rdlen == 4) {
                        memcpy(&out->s_addr, r + p, 4);  /* already network order */
                        rc = PCNET_OK;
                        goto done;
                    }
                    p += rdlen;
                }
                rc = PCNET_EHOSTUNREACH;
                goto done;
            }
            __asm__ __volatile__("hlt");   /* yield until next IRQ */
        }
        rc = PCNET_ETIMEDOUT;
    }

done:
    ops->sock_close(cookie);
    return rc;
}

/* ------------------------------------------------------------------
 * Syscall dispatch — entered from idt.c when INT 0x80 fires.
 * frame->ebx held the caller's pointer to net_syscall_frame; idt.c
 * casts and calls us directly. We read op, translate fd args -> cookies,
 * invoke the active provider's vtable, write the result into frame->ret.
 * ------------------------------------------------------------------ */

/* Pointer-typed args within a frame are offsets in the caller's DS.
 * XPTR translates to linear by adding ds_base (0 for kernel callers).
 * NULL is preserved as NULL. Cast through unsigned long is robust on
 * i386 where sizeof(void *) == sizeof(unsigned long) == sizeof(uint32_t). */
#define XPTR(t, x)  ((t)(unsigned long)((x) ? ((x) + ds_base) : 0))

void net_dispatch(struct net_syscall_frame *f, uint32_t ds_base) {
    const struct net_provider_ops *ops;
    pcnet_sock_t cookie;

    if (!f) return;

    if (!g_active) { f->ret = PCNET_ENOPROVIDER; return; }
    ops = g_active->ops;

    switch (f->op) {

    case NET_SYS_SOCKET: {
        pcnet_sock_t c;
        int rc;
        if (!ops->sock_create) { f->ret = PCNET_ENOSYS; break; }
        rc = ops->sock_create((int)f->a0, (int)f->a1, (int)f->a2, &c);
        if (rc < 0) { f->ret = rc; break; }
        f->ret = fd_alloc(c);
        if (f->ret < 0 && ops->sock_close) ops->sock_close(c);
        break;
    }

    case NET_SYS_CLOSE: {
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_close ? ops->sock_close(cookie) : PCNET_OK;
        fd_free((int)f->a0);
        break;
    }

    case NET_SYS_SHUTDOWN:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_shutdown
            ? ops->sock_shutdown(cookie, (int)f->a1)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_BIND:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_bind
            ? ops->sock_bind(cookie,
                             XPTR(const struct sockaddr *, f->a1),
                             (pcnet_socklen_t)f->a2)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_CONNECT:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_connect
            ? ops->sock_connect(cookie,
                                XPTR(const struct sockaddr *, f->a1),
                                (pcnet_socklen_t)f->a2)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_LISTEN:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_listen
            ? ops->sock_listen(cookie, (int)f->a1)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_ACCEPT: {
        pcnet_sock_t new_c;
        int rc;
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        if (!ops->sock_accept) { f->ret = PCNET_ENOSYS; break; }
        rc = ops->sock_accept(cookie, &new_c,
                              XPTR(struct sockaddr *, f->a1),
                              XPTR(pcnet_socklen_t *, f->a2));
        if (rc < 0) { f->ret = rc; break; }
        f->ret = fd_alloc(new_c);
        if (f->ret < 0 && ops->sock_close) ops->sock_close(new_c);
        break;
    }

    case NET_SYS_GETSOCKNAME:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_getsockname
            ? ops->sock_getsockname(cookie,
                                    XPTR(struct sockaddr *, f->a1),
                                    XPTR(pcnet_socklen_t *, f->a2))
            : PCNET_ENOSYS;
        break;

    case NET_SYS_GETPEERNAME:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_getpeername
            ? ops->sock_getpeername(cookie,
                                    XPTR(struct sockaddr *, f->a1),
                                    XPTR(pcnet_socklen_t *, f->a2))
            : PCNET_ENOSYS;
        break;

    case NET_SYS_SEND:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_send
            ? (int32_t)ops->sock_send(cookie,
                                      XPTR(const void *, f->a1),
                                      f->a2, (int)f->a3)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_RECV:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_recv
            ? (int32_t)ops->sock_recv(cookie,
                                      XPTR(void *, f->a1),
                                      f->a2, (int)f->a3)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_SENDTO:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_sendto
            ? (int32_t)ops->sock_sendto(cookie,
                                        XPTR(const void *, f->a1),
                                        f->a2, (int)f->a3,
                                        XPTR(const struct sockaddr *, f->a4),
                                        (pcnet_socklen_t)f->a5)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_RECVFROM:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_recvfrom
            ? (int32_t)ops->sock_recvfrom(cookie,
                                          XPTR(void *, f->a1),
                                          f->a2, (int)f->a3,
                                          XPTR(struct sockaddr *, f->a4),
                                          XPTR(pcnet_socklen_t *, f->a5))
            : PCNET_ENOSYS;
        break;

    case NET_SYS_SELECT: {
        /* a0=nfds, a1=&rdset, a2=&wrset, a3=&exset, a4=&tv (ignored v1).
         * Kernel iterates the fd_set, calls provider's sock_poll per
         * cookie, ORs the result back. No blocking: select returns
         * immediately with the snapshot. Real timeout/blocking is v0.2. */
        pcnet_fd_set *rd = XPTR(pcnet_fd_set *, f->a1);
        pcnet_fd_set *wr = XPTR(pcnet_fd_set *, f->a2);
        pcnet_fd_set *ex = XPTR(pcnet_fd_set *, f->a3);
        pcnet_fd_set rd_out, wr_out, ex_out;
        int nfds = (int)f->a0;
        int fd, n_ready = 0;

        if (!ops->sock_poll) { f->ret = PCNET_ENOSYS; break; }
        if (nfds < 0) nfds = 0;
        if (nfds > PCNET_FD_SETSIZE) nfds = PCNET_FD_SETSIZE;

        PCNET_FD_ZERO(&rd_out);
        PCNET_FD_ZERO(&wr_out);
        PCNET_FD_ZERO(&ex_out);

        for (fd = 0; fd < nfds; fd++) {
            int want = 0, got;
            if (rd && PCNET_FD_ISSET(fd, rd)) want |= PCNET_POLL_RD;
            if (wr && PCNET_FD_ISSET(fd, wr)) want |= PCNET_POLL_WR;
            if (ex && PCNET_FD_ISSET(fd, ex)) want |= PCNET_POLL_EX;
            if (!want) continue;
            if (!g_fdtab[fd].in_use) continue;

            got = ops->sock_poll(g_fdtab[fd].cookie);
            if (got < 0) continue;

            if (got & want & PCNET_POLL_RD) { PCNET_FD_SET(fd, &rd_out); n_ready++; }
            if (got & want & PCNET_POLL_WR) { PCNET_FD_SET(fd, &wr_out); n_ready++; }
            if (got & want & PCNET_POLL_EX) { PCNET_FD_SET(fd, &ex_out); n_ready++; }
        }
        if (rd) *rd = rd_out;
        if (wr) *wr = wr_out;
        if (ex) *ex = ex_out;
        f->ret = n_ready;
        break;
    }

    case NET_SYS_SETSOCKOPT:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_setsockopt
            ? ops->sock_setsockopt(cookie, (int)f->a1, (int)f->a2,
                                   XPTR(const void *, f->a3),
                                   (pcnet_socklen_t)f->a4)
            : PCNET_ENOSYS;
        break;

    case NET_SYS_GETSOCKOPT:
        if (fd_lookup((int)f->a0, &cookie) < 0) { f->ret = PCNET_EBADF; break; }
        f->ret = ops->sock_getsockopt
            ? ops->sock_getsockopt(cookie, (int)f->a1, (int)f->a2,
                                   XPTR(void *, f->a3),
                                   XPTR(pcnet_socklen_t *, f->a4))
            : PCNET_ENOSYS;
        break;

    case NET_SYS_RESOLVE:
        f->ret = net_resolve(XPTR(const char *, f->a0),
                             XPTR(struct in_addr *, f->a1));
        break;

    default:
        f->ret = PCNET_ENOSYS;
        break;
    }
}

/* ------------------------------------------------------------------
 * Boot wiring — clear state, install the INT 0x80 IDT gate with DPL=3
 * so Ring-3 PM DPMI clients can call it without #GP. Must be called
 * before any provider attempts registration (i.e. before .kmd loads
 * named in PCORE.CFG).
 * ------------------------------------------------------------------ */
void net_init(void) {
    int i;
    g_active = NULL;
    for (i = 0; i < PCNET_FD_SETSIZE; i++) {
        g_fdtab[i].in_use = 0;
        g_fdtab[i].cookie = NULL;
    }
    idt_set_gate(0x80, (uint32_t)isr_stub_128, 0x08, IDT_GATE_INT3);
    serial_puts("net: subsystem ready (INT 0x80 DPL=3, fd cap ");
    /* small inline u16 -> decimal printer; avoid pulling in printf */
    {
        char buf[8];
        int n = PCNET_FD_SETSIZE, len = 0;
        char tmp[8]; int j = 0;
        if (n == 0) tmp[j++] = '0';
        while (n) { tmp[j++] = '0' + (n % 10); n /= 10; }
        while (j) buf[len++] = tmp[--j];
        buf[len] = 0;
        serial_puts(buf);
    }
    serial_puts(")\n");
}

/* ------------------------------------------------------------------
 * Kernel exports for .kmd providers. Colocated with the code per the
 * pattern called out in kexports.c. LGPL-friendly (not GPL-only) so
 * closed providers can link.
 * ------------------------------------------------------------------ */
EXPORT_SYMBOL(net_register_provider);
EXPORT_SYMBOL(net_unregister_provider);
EXPORT_SYMBOL(net_active_provider);
EXPORT_SYMBOL(net_resolve);
